openapi: 3.0.0
info:
  description: "Signout REST"
  version: "1.0.0"
  title: "Signout REST"
  contact:
    email: "jon@community-boating.org"
paths:
  /staff/dockhouse/grant-ratings:
    get:
      summary: "Grant ratings"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GrantRatingsRequest"
  /staff/dockhouse/dh-globals:
    get:
      summary: "Get DH global values"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DockhouseGlobals"
  /staff/dockhouse/put-flag-change:
    get:
      summary: "Get DH global values"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  flagColor:
                    type: string
                    enum: [G,Y,R,C]
  /staff/dockhouse/scan-card:
    get:
      summary: "Scan a card to fetch person info"
      parameters:
        - in: query
          name: cardNumber
          schema:
            type: integer
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardScanResult"
  /staff/dockhouse/create-signout:
    post:
      summary: "Attempt to create a signout"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSignout"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Signout"
  /rest/signouts-today:
    get:
      summary: "Get today's signouts"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Signout"
  /rest/signout:
    post:
      summary: "Update a signout"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Signout"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Signout"
  /rest/ap-class-sessions/today:
    get:
      summary: "Get today's class sessions"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApClassSession"
components:
  schemas:
    GrantRatingsRequest:
      type: object
      properties:
        instructor:
          type: string
        programId:
          type: number
        personIds:
          type: array
          items:
            type: number
        ratingIds:
          type: array
          items:
            type: number
    FlagColorHistory:
      type: object
      properties:
        flag:
          type: string
        changeDatetime:
          type: string
    DockhouseAnnouncement:
      type: object
      properties:
        message:
          type: string
        priority:
          type: string
    DockhouseGlobals:
      type: object
      properties:
        serverDateTime:
          type: string
        sunsetTime:
          type: string
        windSpeedAvg:
          type: number
        winDir:
          type: string
        announcements:
          type: array
          items:
            $ref: "#/components/schemas/DockhouseAnnouncement"
        flagChanges:
          type: array
          items:
            $ref: "#/components/schemas/CardScanResultRating"
    CardScanResultMembership:
      type: object
      properties:
        assignId:
          type: number
        membershipTypeId:
          type: number
        startDate:
          nullable: true
          type: string
        expirationDate:
          nullable: true
          type: string
        discountName:
          nullable: true
          type: string
        isDiscountFrozen:
          type: boolean
        hasGuestPrivs:
          type: boolean
        bannerComment:
          type: string
          nullable: true
        signoutBlockReason:
          type: string
          nullable: true
    CardScanResultRating:
      type: object
      properties:
        ratingId:
          type: number
        programId:
          type: number
        ratingName:
          type: string
        status:
          type: string
          enum: [Y,F]
    CardScanResult:
      type: object
      properties:
        personId:
          type: number
        cardNumber:
          type: string
        nameFirst:
          type: string
        nameLast:
          type: string
        bannerComment:
          nullable: true
          type: string
        specialNeeds:
          nullable: true
          type: string
        activeMemberships:
          type: array
          items:
            $ref: "#/components/schemas/CardScanResultMembership"
        personRatings:
          type: array
          items:
            $ref: "#/components/schemas/CardScanResultRating"
        maxFlagsPerBoat:
          type: array
          items:
            type: object
            properties:
              $$boatType:
                type: object
                properties:
                  boatId:
                    type: number
              $$programId:
                type: object
                properties:
                  programId:
                    type: number
              maxFlag:
                type: string
    CreateSignoutCrew:
      type: object
      properties:
        personId:
          type: number
        cardNumber:
          type: string
        testRatingId:
          nullable: true
          type: number
    CreateSignout:
      type: object
      properties:
        skipperPersonId:
          type: number
        programId:
          type: number
        skipperCardNumber:
          type: string
        skipperTestRatingId:
          nullable: true
          type: number
        boatId:
          type: number
        sailNumber:
          nullable: true
          type: string
        hullNumber:
          nullable: true
          type: string
        classSessionId:
          nullable: true
          type: number
        isRacing:
          type: boolean
        dockmasterOverride:
          type: boolean
        didInformKayakRules:
          type: boolean
        signoutCrew:
          type: array
          items:
            $ref: "#/components/schemas/CreateSignoutCrew"
    Signout:
      type: object
      properties:
        signoutId:
          type: number
        programId:
          type: number
        boatId:
          type: number
        personId:
          type: number
        cardNumber:
          type: string
        sailNumber:
          type: string
        hullNumber:
          type: string
        signoutDatetime:
          type: string
        signinDatetime:
          type: string
        testRatingId:
          type: number
        testResult:
          type: string
        signoutType:
          type: string
        didCapsize:
          type: boolean
        comments:
          type: string
        crew:
          type: array
          items:
            $ref: "#/components/schemas/SignoutCrew"
    SignoutCrew:
      type: object
      properties:
        crewId:
          type: number
        signoutId:
          type: number
        cardNumber:
          type: string
        personId:
          type: number
        startActive:
          type: string
        endActive:
          type: string
    ApClassType:
      type: object
      properties:
        signupMinDefault:
          type: number
          nullable: true
        noSignup:
          type: boolean
        disallowIfOverkill:
          type: boolean
        signupMaxDefault:
          type: number
          nullable: true
        typeId:
          type: number
        typeName:
          type: string
        priceDefault:
          type: number
          nullable: true
        displayOrder:
          type: number
    ApClassFormat:
      type: object
      properties:
        sessionLengthDefault:
          type: number
        typeId:
          type: number
        signupMinDefaultOverride:
          type: number
          nullable: true
        signupMaxDefaultOverride:
          type: number
          nullable: true
        formatId:
          type: number
        priceDefaultOverride:
          type: number
          nullable: true
        sessionCtDefault:
          type: number
        $$apClassType:
          $ref: "#/components/schemas/ApClassType"
    ApClassInstance:
      type: object
      properties:
        instanceId:
          type: number
        cancelledDatetime:
          type: string
          nullable: true
        signupsStartOverride:
          type: string
          nullable: true
        signupMin:
          type: number
          nullable: true
        price:
          type: number
          nullable: true
        signupMax:
          type: number
          nullable: true
        formatId:
          type: number
        hideOnline:
          type: boolean
        cancelByOverride:
          type: string
          nullable: true
        locationString:
          type: string
          nullable: true
        $$apClassFormat:
          $ref: "#/components/schemas/ApClassFormat"
    ApClassSession:
      type: object
      properties:
        instanceId:
          type: number
        sessionId:
          type: number
        cancelledDateTime:
          type: string
          nullable: true
        sessionDateTime:
          type: string
        headcount:
          type: number
          nullable: true
        sessionLength:
          type: number
        $$apClassInstance:
          $ref: "#/components/schemas/ApClassInstance"