name: Scala CI

on:
  push:
    branches:
      - master
      - release/*
      - dev/*
      - cluster/*
  pull_request:
    branches:
      - master
      - release/*
      - dev/*
      - cluster/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: generate routes
      run: mkdir conf/routes-build/dist && ./py-build-routes.py 1
    - name: build deb
      run: sbt debian:packageBin
    - name: save artifact
      uses: actions/upload-artifact@v2
      with:
        name: CBI DB API_0.1.0_all.deb
        path: target/CBI DB API_0.1.0_all.deb
