name: Scala CI

on:
  push:
    branches:
      - master
      - release/*
      - dev/*
      - cluster/*
  pull_request:
    branches:
      - master
      - release/*
      - dev/*
      - cluster/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: generate routes
      run: mkdir conf/routes-build/dist && ./py-build-routes.py 1
    - name: build deb
      run: sbt debian:packageBin
    - name: save artifact
      uses: actions/upload-artifact@v2
      with:
        name: CBI-DB-API_0.1.0_all.deb
        path: target/CBI-DB-API_0.1.0_all.deb
  image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Fetch artifact
        uses: actions/download-artifact@v2
        with:
          name: CBI-DB-API_0.1.0_all.deb
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: ls
        run: ls
      - name: build image
        run: docker build -t registry.digitalocean.com/community-boating-docker/cbidb-api:latest .
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: push image
        run: docker push registry.digitalocean.com/community-boating-docker/cbidb-api:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}